# Generated by Django 4.2.16 on 2024-10-06 11:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_visacard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visacard',
            name='cvv',
            field=models.CharField(help_text='يجب أن يكون رقم البطاقة مكونًا من 3 رقمًا', max_length=3, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(3)], verbose_name='رقم البطاقة:'),
        ),
        migrations.AlterField(
            model_name='visacard',
            name='number',
            field=models.CharField(help_text='يجب أن يكون رقم البطاقة مكونًا من 16 رقمًا', max_length=16, validators=[django.core.validators.MinLengthValidator(16), django.core.validators.MaxLengthValidator(16)], verbose_name='رقم البطاقة:'),
        ),
    ]
